"use client";
import{useEffect,useState}from"react";
import{ArrowRight,Clock3,MapPin,Phone,X,Upload,Trash2,LockKeyhole,Utensils,ShoppingBasket,ChevronLeft,ChevronRight,BookOpen,ImagePlus,Plus}from"lucide-react";
type Photo={id:string;src:string;alt:string};
type MenuItem={id:string;title:string;description:string;price:string;image:string;caption:string};
const gallerySeed:Photo[]=[
{id:"g1",src:"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=85",alt:"Domowe jedzenie"},
{id:"g2",src:"https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=85",alt:"Świeże danie"},
{id:"g3",src:"https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1200&q=85",alt:"Danie z pieca"},
{id:"g4",src:"https://images.unsplash.com/photo-1551218808-94e220e084d2?auto=format&fit=crop&w=1200&q=85",alt:"Kuchnia"},
{id:"g5",src:"https://images.unsplash.com/photo-1466637574441-749b8f19452f?auto=format&fit=crop&w=1200&q=85",alt:"Świeże składniki"},
{id:"g6",src:"https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=85",alt:"Danie domowe"}];
const menuSeed:MenuItem[]=[
{id:"m1",title:"Dania dnia",description:"Obiad jak z niedzielnego stołu, zmieniany według sezonu.",price:"od 24 zł",image:"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=85",caption:"Dzisiejszy obiad, świeżo wydany z kuchni."},
{id:"m2",title:"Zupy",description:"Domowe, długo gotowane i doprawiane bez pośpiechu.",price:"od 12 zł",image:"https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1000&q=85",caption:"Garnek pachnący warzywami, majerankiem i domem."},
{id:"m3",title:"Dania obiadowe",description:"Klasyka polskiej kuchni, porządna porcja i prosty skład.",price:"od 29 zł",image:"https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1000&q=85",caption:"Treściwie, swojsko i tak, jak nakazuje porządny obiad."},
{id:"m4",title:"Pierogi",description:"Ręcznie lepione, z farszami inspirowanymi domową kuchnią.",price:"od 26 zł",image:"https://images.unsplash.com/photo-1498579150354-977475b7de5d?auto=format&fit=crop&w=1000&q=85",caption:"Każdy pieróg składany ręcznie, jeden po drugim."},
{id:"m5",title:"Sałatki i dodatki",description:"Świeże dodatki do obiadu i lekkie propozycje na co dzień.",price:"od 14 zł",image:"https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1000&q=85",caption:"Świeżość prosto z kuchennego stołu."},
{id:"m6",title:"Desery",description:"Słodkie zakończenie inspirowane domowym kredensem.",price:"od 12 zł",image:"https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=1000&q=85",caption:"Na koniec coś słodkiego, najlepiej przy kawie."}];
const heroImage="https://upload.wikimedia.org/wikipedia/commons/a/a0/Aleksander_Kotsis_-_Kitchen_interior_-_MP_4670_MNW_-_National_Museum_in_Warsaw.jpg";
export default function Home(){
const[g,setG]=useState(gallerySeed),[m,setM]=useState(menuSeed),[lb,setLb]=useState<number|null>(null),[owner,setOwner]=useState(false),[logged,setLogged]=useState(false),[pass,setPass]=useState(""),[tab,setTab]=useState<"gallery"|"menu">("gallery");
useEffect(()=>{try{const a=localStorage.getItem("micica-gallery"),b=localStorage.getItem("micica-menu");if(a)setG(JSON.parse(a));if(b)setM(JSON.parse(b))}catch{}},[]);
const saveG=(x:Photo[])=>{setG(x);localStorage.setItem("micica-gallery",JSON.stringify(x))};
const saveM=(x:MenuItem[])=>{setM(x);localStorage.setItem("micica-menu",JSON.stringify(x))};
const addGallery=(files:FileList|null)=>{if(!files)return;Array.from(files).forEach(file=>{const r=new FileReader();r.onload=()=>setG(prev=>{const x=[...prev,{id:crypto.randomUUID(),src:String(r.result),alt:file.name.replace(/\.[^/.]+$/,"")||"Zdjęcie lokalu"}];localStorage.setItem("micica-gallery",JSON.stringify(x));return x});r.readAsDataURL(file)})};
const updateM=(id:string,k:keyof MenuItem,v:string)=>setM(prev=>{const x=prev.map(i=>i.id===id?{...i,[k]:v}:i);localStorage.setItem("micica-menu",JSON.stringify(x));return x});
const addMenuPhoto=(id:string,file:File|undefined)=>{if(!file)return;const r=new FileReader();r.onload=()=>updateM(id,"image",String(r.result));r.readAsDataURL(file)};
const addItem=()=>saveM([...m,{id:crypto.randomUUID(),title:"Nowa pozycja",description:"Opis do uzupełnienia.",price:"od 20 zł",image:menuSeed[0].image,caption:"Dopisz tutaj opowieść do zdjęcia."}]);
const move=(id:string,d:number)=>{const i=m.findIndex(x=>x.id===id),j=i+d;if(i<0||j<0||j>=m.length)return;const x=[...m];[x[i],x[j]]=[x[j],x[i]];saveM(x)};
return <><header><div className="wrap nav"><a className="logo" href="#start"><span>CHATA</span><b>POLSKA MIĆICA</b></a><nav><a href="#o-nas">O nas</a><a href="#menu">Jadłospis</a><a href="#galeria">Galeria</a><a href="#kontakt">Kontakt</a></nav><a className="phone" href="tel:+48000000000"><Phone size={15}/>Zadzwoń</a></div></header>
<section id="start" className="hero"><div className="heroBg"/><div className="wrap heroIn"><span className="eyebrow">RAWICZ · UL. KMICIA 3 · SMAK DAWNEJ POLSKI</span><h1>Stół jak z dawnej<br/><i>Rzeczypospolitej.</i></h1><p>Domowa kuchnia inspirowana polską tradycją, opowieściami z Trylogii i stołem, przy którym człowiek zostaje na dłużej.</p><div className="actions"><a className="btn primary" href="#menu">Przejdź do jadłospisu <ArrowRight/></a><a className="btn ghost" href="#kontakt">Odwiedź nas</a></div></div><div className="recommend"><small>CHATA POLSKA MIĆICA</small><b>Gość w dom, Bóg w dom</b><span>Smak, który ma swoją opowieść.</span></div></section>
<div className="ticker"><span>DAWNE RECEPTURY</span><span>ŚWIEŻE SKŁADNIKI</span><span>DOMOWY STÓŁ</span><span>BEZ ZBĘDNYCH DODATKÓW</span></div>
<section id="o-nas" className="section wrap intro"><div><span className="eyebrow">O NAS</span><h2>Jakby czas zatrzymał się<br/><i>przy rodzinnym stole.</i></h2></div><div className="copy"><p>Chata Polska Mićica łączy delikatesy z kuchnią, w której liczy się smak znany z rodzinnego domu. Inspiracją jest dawna polska gościnność: prostota, dobre produkty i stół, przy którym zawsze znajdzie się miejsce.</p><p>Warstwa wizualna nawiązuje do świata Sienkiewiczowskiej Trylogii: dawnych dworów, ręcznie pisanych jadłospisów, starego papieru, mosiądzu i ciepłego światła kuchni.</p><div className="facts"><span><Utensils/>Domowe gotowanie</span><span><ShoppingBasket/>Świeże produkty</span></div></div></section>
<section id="menu" className="section menuSec"><div className="wrap"><div className="head"><div><span className="eyebrow">JADŁOSPIS</span><h2>Co dziś <i>podajemy?</i></h2></div><small>Każda karta ma własne zdjęcie i opowieść.</small></div><div className="menuCards">{m.map((x,i)=><article className="menuCard" key={x.id}><div className="menuCardImage"><img src={x.image} alt={x.title}/><span>{String(i+1).padStart(2,"0")}</span></div><div className="menuCardBody"><div className="menuCardTop"><h3>{x.title}</h3><b>{x.price}</b></div><p>{x.description}</p><div className="menuCaption">„{x.caption}”</div></div></article>)}</div></div></section>
<section id="galeria" className="section wrap"><div className="head"><div><span className="eyebrow">GALERIA LOKALU</span><h2>Tak wygląda <i>Chata.</i></h2></div><small>Galeria lokalu jest niezależna od zdjęć w menu.</small></div><div className="gallery">{g.map((x,i)=><button key={x.id} className={"photo photo"+i} onClick={()=>setLb(i)}><img src={x.src} alt={x.alt}/></button>)}</div></section>
<section className="quote"><div className="wrap"><div>“</div><blockquote>Dobry stół nie potrzebuje pośpiechu. Potrzebuje ludzi, opowieści i czegoś ciepłego na talerzu.</blockquote><span>✦ ✦ ✦</span></div></section>
<section id="kontakt" className="contact"><div className="wrap contactGrid"><div><span className="eyebrow">ODWIEDŹ NAS</span><h2>Wpadaj na <i>obiad.</i></h2><div className="contactList"><a href="https://www.google.com/maps/search/?api=1&query=ul.+Kmicia+3,+Rawicz"><MapPin/><span><b>ul. Kmicia 3</b><small>Rawicz</small></span></a><a href="tel:+48000000000"><Phone/><span><b>Telefon</b><small>Skontaktuj się z nami</small></span></a><div><Clock3/><span><b>Godziny otwarcia</b><small>Pon.–Pt. 10:00–20:00 · Sob. 10:00–18:00</small></span></div></div><a className="btn primary" href="https://www.google.com/maps/search/?api=1&query=ul.+Kmicia+3,+Rawicz">Wyznacz trasę <ArrowRight/></a></div><div className="map"><iframe title="Mapa" src="https://www.google.com/maps?q=ul.%20Kmicia%203,%20Rawicz&output=embed"/></div></div></section>
<footer><div className="wrap footer"><div className="logo"><span>CHATA</span><b>POLSKA MIĆICA</b></div><p>Tradycyjna kuchnia jak u mamy.<br/>Rawicz · ul. Kmicia 3</p></div><div className="wrap bottom"><span>© 2026 Chata Polska Mićica</span><button onClick={()=>setOwner(true)}><LockKeyhole size={13}/>Panel właściciela</button></div></footer>
{lb!==null&&<div className="lightbox" onClick={()=>setLb(null)}><button className="close" onClick={()=>setLb(null)}><X/></button><button className="arr left" onClick={e=>{e.stopPropagation();setLb((lb-1+g.length)%g.length)}}><ChevronLeft/></button><img src={g[lb].src} alt={g[lb].alt}/><button className="arr right" onClick={e=>{e.stopPropagation();setLb((lb+1)%g.length)}}><ChevronRight/></button></div>}
{owner&&<div className="modal"><div className="owner"><button className="ownerClose" onClick={()=>setOwner(false)}><X/></button>{!logged?<><span className="eyebrow">PANEL WŁAŚCICIELA</span><h2>Gabinet <i>gospodarza.</i></h2><p>Demo zapisuje dane lokalnie w tej przeglądarce. Galeria i menu mają osobne dane i mogą później zostać podłączone do trwałego storage.</p><input type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="Hasło demonstracyjne"/><button className="btn primary full" onClick={()=>pass==="chata-demo"?setLogged(true):alert("Hasło demo: chata-demo")}>Zaloguj</button></>:<><span className="eyebrow">PANEL WŁAŚCICIELA</span><h2>Zarządzaj <i>stroną.</i></h2><div className="adminTabs"><button className={tab==="gallery"?"active":""} onClick={()=>setTab("gallery")}><ImagePlus/>Galeria lokalu</button><button className={tab==="menu"?"active":""} onClick={()=>setTab("menu")}><BookOpen/>Menu i zdjęcia dań</button></div>{tab==="gallery"?<><label className="upload"><Upload/><span><b>Dodaj zdjęcia do galerii</b><small>JPG, PNG, WEBP · tylko galeria lokalu</small></span><input type="file" accept="image/*" multiple onChange={e=>addGallery(e.target.files)}/></label><div className="admin">{g.map(x=><div key={x.id}><img src={x.src} alt={x.alt}/><button onClick={()=>saveG(g.filter(y=>y.id!==x.id))}><Trash2 size={15}/></button></div>)}</div></>:<><div className="menuAdminHeader"><p>Edytuj nazwę, opis, cenę, zdjęcie oraz podpis pod zdjęciem każdego dania.</p><button className="btn primary" onClick={addItem}><Plus size={16}/>Dodaj pozycję</button></div><div className="menuAdminList">{m.map((x,i)=><div className="menuAdminCard" key={x.id}><div className="menuAdminPhoto"><img src={x.image} alt=""/><label><Upload size={15}/>Zmień zdjęcie<input type="file" accept="image/*" onChange={e=>addMenuPhoto(x.id,e.target.files?.[0])}/></label></div><div className="menuAdminFields"><div className="fieldRow"><label>Nazwa<input value={x.title} onChange={e=>updateM(x.id,"title",e.target.value)}/></label><label>Cena<input value={x.price} onChange={e=>updateM(x.id,"price",e.target.value)}/></label></div><label>Opis<textarea value={x.description} onChange={e=>updateM(x.id,"description",e.target.value)}/></label><label>Podpis / opowieść do zdjęcia<textarea value={x.caption} onChange={e=>updateM(x.id,"caption",e.target.value)}/></label><div className="adminActions"><button onClick={()=>move(x.id,-1)} disabled={i===0}>↑ Wyżej</button><button onClick={()=>move(x.id,1)} disabled={i===m.length-1}>↓ Niżej</button><button className="danger" onClick={()=>saveM(m.filter(y=>y.id!==x.id))}><Trash2 size={15}/>Usuń</button></div></div></div>)}</div></>}<button className="logout" onClick={()=>setLogged(false)}><LockKeyhole size={13}/>Wyloguj</button></>}</div></div>}</>}