"use client";
import{useEffect,useState}from"react";import{ArrowRight,Clock3,MapPin,Phone,X,Upload,Trash2,LockKeyhole,Utensils,ShoppingBasket,ChevronLeft,ChevronRight}from"lucide-react";
type Photo={id:string;src:string;alt:string};
const seed:Photo[]=[{id:"1",src:"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=85",alt:"Domowe jedzenie"},{id:"2",src:"https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=85",alt:"Świeże danie"},{id:"3",src:"https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1200&q=85",alt:"Pizza"},{id:"4",src:"https://images.unsplash.com/photo-1551218808-94e220e084d2?auto=format&fit=crop&w=1200&q=85",alt:"Kuchnia"},{id:"5",src:"https://images.unsplash.com/photo-1466637574441-749b8f19452f?auto=format&fit=crop&w=1200&q=85",alt:"Składniki"},{id:"6",src:"https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=85",alt:"Danie"}];
const dishes=[["Dania dnia","Codziennie coś innego, zawsze świeżo","od 24 zł"],["Zupy","Domowe, gotowane na miejscu","od 12 zł"],["Dania obiadowe","Klasyka polskiej kuchni","od 29 zł"],["Pierogi","Ręcznie lepione, tradycyjne farsze","od 26 zł"],["Sałatki i dodatki","Świeże dodatki do obiadu","od 14 zł"],["Desery","Słodkie zakończenie","od 12 zł"]];
export default function Home(){const[p,setP]=useState(seed),[lb,setLb]=useState<number|null>(null),[owner,setOwner]=useState(false),[logged,setLogged]=useState(false),[pass,setPass]=useState("");
useEffect(()=>{const x=localStorage.getItem("micica-gallery");if(x)try{setP(JSON.parse(x))}catch{}},[]);
const save=(x:Photo[])=>{setP(x);localStorage.setItem("micica-gallery",JSON.stringify(x))};
const add=(files:FileList|null)=>{if(!files)return;Array.from(files).forEach(file=>{const r=new FileReader();r.onload=()=>save([...p,{id:crypto.randomUUID(),src:String(r.result),alt:"Zdjęcie lokalu"}]);r.readAsDataURL(file)})};
return <><header><div className="wrap nav"><a className="logo" href="#start"><span>CHATA</span><b>POLSKA MIĆICA</b></a><nav><a href="#o-nas">O nas</a><a href="#menu">Menu</a><a href="#galeria">Galeria</a><a href="#kontakt">Kontakt</a></nav><a className="phone" href="tel:+48000000000"><Phone size={15}/>Zadzwoń</a></div></header>
<section id="start" className="hero"><div className="heroBg"/><div className="wrap heroIn"><span className="eyebrow">RAWICZ · UL. KMICIA 3</span><h1>Tradycyjna kuchnia,<br/><i>jak u mamy.</i></h1><p>Smacznie, świeżo i bez konserwantów. Domowe smaki, porządne składniki i atmosfera, do której chce się wracać.</p><div className="actions"><a className="btn primary" href="#menu">Zobacz menu <ArrowRight/></a><a className="btn ghost" href="#kontakt">Odwiedź nas</a></div></div><div className="recommend"><small>DZISIAJ POLECAMY</small><b>Domowy obiad</b><span>Świeżo przygotowany</span></div></section>
<div className="ticker"><span>ŚWIEŻE SKŁADNIKI</span><span>DOMOWE RECEPTURY</span><span>BEZ KONSERWANTÓW</span><span>CODZIENNIE COŚ DOBREGO</span></div>
<section id="o-nas" className="section wrap intro"><div><span className="eyebrow">O NAS</span><h2>Miejsce stworzone<br/><i>z myślą o dobrym jedzeniu.</i></h2></div><div className="copy"><p>Chata Polska Mićica łączy delikatesy z kuchnią, w której liczy się smak znany z rodzinnego stołu. Gotujemy prosto, świeżo i bez zbędnych dodatków.</p><p>Nazwa zobowiązuje: jesteśmy przy ulicy Kmicia, a nasza kuchnia ma być tak swojska, jak sugeruje adres.</p><div className="facts"><span><Utensils/>Domowe gotowanie</span><span><ShoppingBasket/>Świeże produkty</span></div></div></section>
<section id="menu" className="section menuSec"><div className="wrap"><div className="head"><div><span className="eyebrow">MENU</span><h2>Co dziś <i>dobrego?</i></h2></div><small>Oferta może zmieniać się sezonowo</small></div><div className="menuGrid">{dishes.map((d,i)=><article key={i}><span>0{i+1}</span><div><h3>{d[0]}</h3><p>{d[1]}</p></div><b>{d[2]}</b></article>)}</div></div></section>
<section id="galeria" className="section wrap"><div className="head"><div><span className="eyebrow">GALERIA</span><h2>Tak wygląda <i>Chata.</i></h2></div><small>Kliknij zdjęcie, aby powiększyć.</small></div><div className="gallery">{p.map((x,i)=><button key={x.id} className={"photo photo"+i} onClick={()=>setLb(i)}><img src={x.src} alt={x.alt}/></button>)}</div></section>
<section className="quote"><div className="wrap"><div>“</div><blockquote>Najlepsze jedzenie to takie, które nie musi niczego udawać.</blockquote><span>★★★★★</span></div></section>
<section id="kontakt" className="contact"><div className="wrap contactGrid"><div><span className="eyebrow">ODWIEDŹ NAS</span><h2>Wpadaj na <i>obiad.</i></h2><div className="contactList"><a href="https://www.google.com/maps/search/?api=1&query=ul.+Kmicia+3,+Rawicz"><MapPin/><span><b>ul. Kmicia 3</b><small>Rawicz</small></span></a><a href="tel:+48000000000"><Phone/><span><b>Telefon</b><small>Skontaktuj się z nami</small></span></a><div><Clock3/><span><b>Godziny otwarcia</b><small>Pon.–Pt. 10:00–20:00 · Sob. 10:00–18:00</small></span></div></div><a className="btn primary" href="https://www.google.com/maps/search/?api=1&query=ul.+Kmicia+3,+Rawicz">Wyznacz trasę <ArrowRight/></a></div><div className="map"><iframe title="Mapa" src="https://www.google.com/maps?q=ul.%20Kmicia%203,%20Rawicz&output=embed"/></div></div></section>
<footer><div className="wrap footer"><div className="logo"><span>CHATA</span><b>POLSKA MIĆICA</b></div><p>Tradycyjna kuchnia jak u mamy.<br/>Rawicz · ul. Kmicia 3</p></div><div className="wrap bottom"><span>© 2026 Chata Polska Mićica</span><button onClick={()=>setOwner(true)}><LockKeyhole size={13}/>Panel właściciela</button></div></footer>
{lb!==null&&<div className="lightbox" onClick={()=>setLb(null)}><button className="close" onClick={()=>setLb(null)}><X/></button><button className="arr left" onClick={e=>{e.stopPropagation();setLb((lb-1+p.length)%p.length)}}><ChevronLeft/></button><img src={p[lb].src} alt={p[lb].alt}/><button className="arr right" onClick={e=>{e.stopPropagation();setLb((lb+1)%p.length)}}><ChevronRight/></button></div>}
{owner&&<div className="modal"><div className="owner"><button className="close" onClick={()=>setOwner(false)}><X/></button>{!logged?<><span className="eyebrow">PANEL WŁAŚCICIELA</span><h2>Zarządzaj <i>galerią.</i></h2><p>Wersja demonstracyjna zapisuje zdjęcia lokalnie w przeglądarce. Kod jest przygotowany do późniejszego podłączenia trwałego storage, np. Supabase.</p><input type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="Hasło demonstracyjne"/><button className="btn primary full" onClick={()=>pass==="chata-demo"?setLogged(true):alert("Hasło demo: chata-demo")}>Zaloguj</button></>:<><span className="eyebrow">PANEL WŁAŚCICIELA</span><h2>Twoja <i>galeria.</i></h2><label className="upload"><Upload/><b>Dodaj zdjęcia</b><small>JPG, PNG, WEBP</small><input type="file" accept="image/*" multiple onChange={e=>add(e.target.files)}/></label><div className="admin">{p.map(x=><div key={x.id}><img src={x.src} alt=""/><button onClick={()=>save(p.filter(y=>y.id!==x.id))}><Trash2 size={15}/></button></div>)}</div><button className="logout" onClick={()=>setLogged(false)}>Wyloguj</button></>}</div></div>}</>}